'use strict';function v(f,a,b,d){f.u.vc(f.bb,a,b,d,void 0)}function E(f,a,b,d){f.u.ca?v(f,a,b,d):f.u.Df()._OnMessageFromDOM({type:"event",component:f.bb,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function F(f,a,b){f.u.C(f.bb,a,b)}function K(f,a){for(const [b,d]of a)F(f,b,d)}function L(f){f.Vb||(f.u.mf(f.te),f.Vb=!0)}window.Ta=class{constructor(f,a){this.u=f;this.bb=a;this.Vb=!1;this.te=()=>this.wa()}rd(){}wa(){}};function N(f){-1!==f.Qa&&(self.clearTimeout(f.Qa),f.Qa=-1)}
window.bf=class{constructor(f,a){this.Wc=f;this.Zg=a;this.Qa=-1;this.Wb=-Infinity;this.ue=()=>{this.Qa=-1;this.Wb=Date.now();this.hb=!0;this.Wc();this.hb=!1};this.Zd=this.hb=!1}f(){N(this);this.ue=this.Wc=null}};"use strict";
function O(f,a){const b=a.elementId,d=f.vd(b,a);f.Y.set(b,d);d.style.boxSizing="border-box";a.isVisible||(d.style.display="none");a=f.Fc(d);a.addEventListener("focus",()=>{P(f,"elem-focused",b)});a.addEventListener("blur",()=>{P(f,"elem-blurred",b)});f.Qb&&document.body.appendChild(d)}function Q(f,a){F(f,"get-element",b=>{const d=f.Y.get(b.elementId);return a(d,b)})}function P(f,a,b){var d;d||(d={});d.elementId=b;v(f,a,d)}
window.Ne=class extends self.Ta{constructor(f,a){super(f,a);this.Y=new Map;this.Qb=!0;K(this,[["create",b=>O(this,b)],["destroy",b=>{{b=b.elementId;const d=this.Y.get(b);this.Qb&&d.parentElement.removeChild(d);this.Y.delete(b)}}],["set-visible",b=>{this.Qb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Qb){var d=this.Y.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=b.height+"px";b=b.fontSize;
null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{{const d=this.Y.get(b.elementId);this.Bc(d,b)}}],["focus",b=>this.Qc(b)],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);Q(this,b=>b)}vd(){throw Error("required override");}Bc(){throw Error("required override");}Fc(f){return f}Qc(f){const a=this.Fc(this.Y.get(f.elementId));
f.focus?a.focus():a.blur()}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),a=/android/i.test(navigator.userAgent);let b=0;function d(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.kh?new Promise(k=>{const l="c3_resolve_"+b;++b;self[l]=k;c.textContent=m.oh+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let g=!1,n=!1;function q(){if(!g){try{new Worker("blob://",{get type(){n=
!0}})}catch(m){}g=!0}return n}let w=new Audio;const B={"audio/webm; codecs=opus":!!w.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!w.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!w.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!w.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!w.canPlayType("audio/mp4"),"audio/mpeg":!!w.canPlayType("audio/mpeg")};w=null;async function D(m){m=await x(m);return(new TextDecoder("utf-8")).decode(m)}
function x(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=p=>c(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(m)})}const y=[];let C=0;window.RealFile=window.File;const G=[],A=new Map,H=new Map;let J=0;const M=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");M.push(m)};const e=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.na=class m{constructor(c){this.ca=c.qh;this.ra=null;this.F="";this.jc=c.nh;
this.xb={};this.Ja=this.wb=null;this.Tb=[];this.G=this.Oa=null;this.ee=!1;this.kb=null;this.Na=-1;this.eh=()=>this.gg();this.Ma=[];this.s=c.ve;this.ib="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&q()||(this.ca=!1);if("playable-ad"===this.s||"instant-games"===this.s)this.ca=!1;if("cordova"===this.s&&this.ca)if(a){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.ca=!1)}else this.ca=!1;this.Zb=this.ia=
null;"html5"!==this.s&&"playable-ad"!==this.s||!this.ib||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.s||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",k=>this.Lf(k));
this.C("runtime","create-job-worker",()=>this.Mf());"cordova"===this.s?document.addEventListener("deviceready",()=>this.Md(c)):this.Md(c)}f(){this.Cc();this.ra&&(this.ra=this.ra.onmessage=null);this.wb&&(this.wb.terminate(),this.wb=null);this.Ja&&(this.Ja.f(),this.Ja=null);this.G&&(this.G.parentElement.removeChild(this.G),this.G=null)}Xe(){return f&&"cordova"===this.s}uc(){const c=navigator.userAgent;return f&&e.has(this.s)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}Ve(){return a}zd(){return a&&
e.has(this.s)}async Md(c){"macos-wkwebview"===this.s&&this.Uc({type:"ready"});if("playable-ad"===this.s){this.ia=self.c3_base64files;this.Zb={};await this.sf();for(let l=0,p=c.Ra.length;l<p;++l){var k=c.Ra[l].toLowerCase();this.Zb.hasOwnProperty(k)?c.Ra[l]={kh:!0,oh:this.Zb[k]}:this.ia.hasOwnProperty(k)&&(c.Ra[l]=URL.createObjectURL(this.ia[k]))}}c.fh?this.F=c.fh:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));
c.sh&&(this.xb=c.sh);k=new MessageChannel;this.ra=k.port1;this.ra.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.cg(l));this.kb=new self.Ye(this);await R(this.kb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.Gf(c,k.port2):await this.Ff(c,k.port2)}Gc(c){c=this.xb.hasOwnProperty(c)?this.xb[c]:c.endsWith("/workermain.js")&&
this.xb.hasOwnProperty("workermain.js")?this.xb["workermain.js"]:"playable-ad"===this.s&&this.ia.hasOwnProperty(c.toLowerCase())?this.ia[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async oc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.s&&this.ib)return c=await this.yb(l.jh?c:this.jc+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");
c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}pa(){return Math.max(window.innerWidth,1)}fa(){return Math.max(window.innerHeight,1)}Jd(c){var k=this.kb;return{baseUrl:this.F,previewUrl:location.href,windowInnerWidth:this.pa(),windowInnerHeight:this.fa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:m.Wa(),projectData:c.zh,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,
swClientId:window.xh||"",exportType:c.ve,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.yh,jobScheduler:{inputPort:k.cd,outputPort:k.kd,maxNumWorkers:k.ah},supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.jc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.jc+"opus.wasm.wasm",isFileProtocol:this.ib,isiOSCordova:this.Xe(),isiOSWebView:this.uc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Gf(c,k){var l=this.Gc(c.rh);this.wb=
await this.oc(l,this.F,{type:"module",name:"Runtime",jh:!0});this.G=document.createElement("canvas");this.G.style.display="none";l=this.G.transferControlToOffscreen();document.body.appendChild(this.G);window.c3canvas=this.G;let p=c.qd||[],u=c.Ra;p=await Promise.all(p.map(r=>this.Ea(r)));u=await Promise.all(u.map(r=>this.Ea(r)));if("cordova"===this.s)for(let r=0,t=c.mc.length;r<t;++r){const z=c.mc[r],I=z[0];if(I===c.od||"scriptsInEvents.js"===I||I.endsWith("/scriptsInEvents.js"))z[1]=await this.Ea(I)}this.wb.postMessage(Object.assign(this.Jd(c),
{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:p,engineScripts:u,projectScripts:c.mc,mainProjectScript:c.od,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...S(this.kb)]);this.Tb=G.map(r=>new r(this));this.Id();self.c3_callFunction=(r,t)=>this.Oa.Hf(r,t);"preview"===this.s&&(self.goToLastErrorScript=()=>this.vc("runtime","go-to-last-error-script"))}async Ff(c,k){this.G=document.createElement("canvas");this.G.style.display="none";document.body.appendChild(this.G);
window.c3canvas=this.G;this.Tb=G.map(r=>new r(this));this.Id();var l=c.Ra.map(r=>"string"===typeof r?(new URL(r,this.F)).toString():r);Array.isArray(c.qd)&&l.unshift(...c.qd);l=await Promise.all(l.map(r=>this.Ea(r)));await Promise.all(l.map(r=>d(r)));l=self.C3_ProjectScriptsStatus;const p=c.od,u=c.mc;for(let [r,t]of u)if(t||(t=r),r===p)try{t=await this.Ea(t),await d(t),"preview"!==this.s||l[r]||this.Ud(r,"main script did not run to completion")}catch(z){this.Ud(r,z)}else if("scriptsInEvents.js"===
r||r.endsWith("/scriptsInEvents.js"))t=await this.Ea(t),await d(t);"preview"===this.s&&"object"!==typeof self.th.uh?(this.Lb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Jd(c),{isInWorker:!1,messagePort:k,canvas:this.G,runOnStartupFunctions:M}),this.Od(),this.Ja=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ja,
c))}Ud(c,k){this.Lb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Od(){this.Lb()}Lb(){const c=window.gh;c&&(c.parentElement.removeChild(c),window.gh=null)}async Mf(){const c=await T(this.kb);return{outputPort:c,transferables:[c]}}Df(){if(this.ca)throw Error("not available in worker mode");return this.Ja}vc(c,k,l,p,u){this.ra.postMessage({type:"event",
component:c,handler:k,dispatchOpts:p||null,data:l,responseId:null},u)}Bd(c,k,l,p,u){const r=J++,t=new Promise((z,I)=>{H.set(r,{resolve:z,reject:I})});this.ra.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:r},u);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.Rf(c);if("result"===k)this.kg(c);else if("runtime-ready"===k)this.lg();else if("alert-error"===k)this.Lb(),alert(c.message);else if("creating-runtime"===k)this.Od();else throw Error(`unknown message '${k}'`);
}Rf(c){const k=c.component,l=c.handler,p=c.data,u=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(p)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==u&&this.Kb(u,!1,""+t);return}if(null===u)return r;r&&r.then?r.then(t=>this.Kb(u,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Kb(u,!1,""+t)}):this.Kb(u,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Kb(c,
k,l){let p;l&&l.transferables&&(p=l.transferables);this.ra.postMessage({type:"result",responseId:c,isOk:k,result:l},p)}kg(c){const k=c.responseId,l=c.isOk;c=c.result;const p=H.get(k);l?p.resolve(c):p.reject(c);H.delete(k)}C(c,k,l){let p=A.get(c);p||(p=new Map,A.set(c,p));if(p.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);p.set(k,l)}static Sa(c){if(G.includes(c))throw Error("DOM handler already added");G.push(c)}Id(){for(const c of this.Tb)if("runtime"===c.bb){this.Oa=c;return}throw Error("cannot find runtime DOM handler");
}cg(c){this.vc("debugger","message",c)}lg(){for(const c of this.Tb)c.rd()}static Wa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||h)}static Mb(c){h=!!c}mf(c){this.Ma.push(c);this.Tc()}yg(c){c=this.Ma.indexOf(c);if(-1===c)throw Error("invalid callback");this.Ma.splice(c,1);this.Ma.length||this.Cc()}Tc(){-1===this.Na&&this.Ma.length&&(this.Na=requestAnimationFrame(this.eh))}Cc(){-1!==this.Na&&(cancelAnimationFrame(this.Na),this.Na=-1)}gg(){this.Na=
-1;for(const c of this.Ma)c();this.Tc()}xa(c){this.Oa.xa(c)}Da(c){this.Oa.Da(c)}Sc(){this.Oa.Sc()}Eb(c){this.Oa.Eb(c)}We(){return!!B["audio/webm; codecs=opus"]}async Xg(c){c=await this.Bd("runtime","opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}ef(){this.ee=!0}Ue(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}Ad(c){return!this.Ue(c)}async Ea(c){return"cordova"===this.s&&(c.startsWith("file:")||this.ib&&this.Ad(c))?(c.startsWith(this.F)&&
(c=c.substr(this.F.length)),c=await this.yb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async Lf(c){const k=c.filename;switch(c.as){case "text":return await this.Me(k);case "buffer":return await this.yb(k);default:throw Error("unsupported type");}}ud(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(l,p)},p)})}async Me(c){c=await this.ud(c);return await D(c)}Dc(){if(y.length&&
!(8<=C)){C++;var c=y.shift();this.tf(c.filename,c.ph,c.ih)}}yb(c){return new Promise((k,l)=>{y.push({filename:c,ph:p=>{C--;this.Dc();k(p)},ih:p=>{C--;this.Dc();l(p)}});this.Dc()})}async tf(c,k,l){try{const p=await this.ud(c),u=await x(p);k(u)}catch(p){l(p)}}Uc(c){if("windows-webview2"===this.s)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.s)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");
}async sf(){const c=[];for(const [k,l]of Object.entries(this.ia))c.push(this.rf(k,l));await Promise.all(c)}async rf(c,k){if("object"===typeof k)this.ia[c]=new Blob([k.str],{type:k.type}),this.Zb[c]=k.str;else{let l=await this.Bf(k);l||(l=this.vf(k));this.ia[c]=l}}async Bf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}vf(c){c=this.sg(c);return this.qf(c.data,c.lh)}sg(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||"";const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{lh:c,data:l}}qf(c,k){var l=c.length;let p=l>>2,u=new Uint8Array(l),r=new Uint32Array(u.buffer,0,p),t,z;for(z=t=0;t<p;++t)r[t]=c.charCodeAt(z++)|c.charCodeAt(z++)<<8|c.charCodeAt(z++)<<16|c.charCodeAt(z++)<<24;for(l&=
3;l--;)u[z]=c.charCodeAt(z),++z;return new Blob([u],{type:k})}}}"use strict";
{const f=self.na;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(e){return new Promise((h,m)=>{const c=document.createElement("link");c.onload=()=>h(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=e;document.head.appendChild(c)})}function w(e){return new Promise((h,m)=>{const c=new Image;c.onload=()=>h(c);c.onerror=k=>m(k);c.src=e})}async function B(e){e=URL.createObjectURL(e);try{return await w(e)}finally{URL.revokeObjectURL(e)}}function D(e){return new Promise((h,m)=>{let c=new FileReader;c.onload=k=>h(k.target.result);c.onerror=k=>m(k);c.readAsText(e)})}async function x(e,h,m){if(!/firefox/i.test(navigator.userAgent))return await B(e);var c=await D(e);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),p=k.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await B(e)}k.setAttribute("width",h+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);e=new Blob([c],{type:"image/svg+xml"});return await B(e)}function y(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),G=new Set(["canvas","body","html"]);function A(e){G.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function H(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await B(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,m,c,k){e=await x(e,h,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(e,0,0,h,m);return l};let J=!1;document.addEventListener("pause",()=>J=!0);document.addEventListener("resume",()=>J=!1);function M(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.Sa(class extends self.Ta{constructor(e){super(e,"runtime");this.fe=!0;this.Pa=-1;this.md="any";this.Vd=this.Wd=!1;this.za=
null;this.ae="";this.Zc=-1;this.Ia=this.sb=null;this.ec=this.dc=0;this.ke=e.pa();this.Xb=e.fa();this.ub=0;e.C("canvas","update-size",c=>this.og(c));e.C("runtime","invoke-download",c=>this.ag(c));e.C("runtime","raster-svg-image",c=>this.hg(c));e.C("runtime","get-svg-image-size",c=>this.Zf(c));e.C("runtime","set-target-orientation",c=>this.mg(c));e.C("runtime","register-sw",()=>this.jg());e.C("runtime","post-to-debugger",c=>this.Qd(c));e.C("runtime","go-to-script",c=>this.Qd(c));e.C("runtime","before-start-ticking",
()=>this.Kf());e.C("runtime","debug-highlight",c=>this.Nf(c));e.C("runtime","enable-device-orientation",()=>this.pf());e.C("runtime","enable-device-motion",()=>this.nf());e.C("runtime","add-stylesheet",c=>this.Jf(c));e.C("runtime","alert",c=>this.Kc(c));e.C("runtime","hide-cordova-splash",()=>this.$f());e.C("runtime","set-exporting-to-video",c=>this.Eg(c));e.C("runtime","export-to-video-progress",c=>this.Sf(c));e.C("runtime","exported-to-video",c=>this.Tf(c));const h=new Set(["input","textarea","datalist"]);
window.addEventListener("contextmenu",c=>{const k=c.target;h.has(k.tagName.toLowerCase())||y(k)||c.preventDefault()});const m=e.G;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",A)):m.addEventListener("touchstart",A);this.pb=
0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",H,{passive:!1});window.addEventListener("wheel",H,{passive:!1});window.addEventListener("resize",()=>this.pg());window.addEventListener("fullscreenchange",()=>this.Ya());window.addEventListener("webkitfullscreenchange",()=>this.Ya());window.addEventListener("mozfullscreenchange",()=>this.Ya());window.addEventListener("fullscreenerror",c=>this.Nc(c));window.addEventListener("webkitfullscreenerror",
c=>this.Nc(c));window.addEventListener("mozfullscreenerror",c=>this.Nc(c));if(e.uc())if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const k=window.visualViewport.height;k>c&&(document.scrollingElement.scrollTop=0);c=k})}else window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||
"text"):y(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.rg(c);this.Ka=new Set;this.$b=new WeakSet;this.qa=!1}Kf(){"cordova"===this.u.s?(document.addEventListener("pause",()=>this.Rc(!0)),document.addEventListener("resume",()=>this.Rc(!1))):document.addEventListener("visibilitychange",()=>this.Rc(document.hidden));return{isSuspended:!(!document.hidden&&!J)}}rd(){window.addEventListener("focus",()=>this.$a("window-focus"));window.addEventListener("blur",()=>
{this.$a("window-blur",{parentHasFocus:M()});this.pb=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||y(h))&&this.$a("keyboard-blur")});window.addEventListener("keydown",h=>this.Pd("keydown",h));window.addEventListener("keyup",h=>this.Pd("keyup",h));window.addEventListener("dblclick",h=>this.Oc("dblclick",h,d));window.addEventListener("wheel",h=>this.eg(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",h=>{this.Hc(h);this.Za("pointerdown",
h)}),this.u.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.sb=new self.bf(()=>this.yf(),5),this.sb.Zd=!0,window.addEventListener("pointerrawupdate",h=>this.fg(h))):window.addEventListener("pointermove",h=>this.Za("pointermove",h)),window.addEventListener("pointerup",h=>this.Za("pointerup",h)),window.addEventListener("pointercancel",h=>this.Za("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.Hc(h);this.Pc("pointerdown",h)}),window.addEventListener("mousemove",
h=>this.Pc("pointermove",h)),window.addEventListener("mouseup",h=>this.Pc("pointerup",h)),window.addEventListener("touchstart",h=>{this.Hc(h);this.Jb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Jb("pointermove",h)),window.addEventListener("touchend",h=>this.Jb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Jb("pointercancel",h)));const e=()=>this.Sc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",e,!0);window.addEventListener("click",
e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0);this.u.Ve()&&!this.u.zd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this.Lc(this.fa(),navigator.virtualKeyboard.boundingRect.height)}))}Lc(e,h){document.body.style.transform="";if(0<h){var m=document.activeElement;m&&(m=m.getBoundingClientRect(),e=(m.top+m.bottom)/2-(e-h)/2,e>h&&(e=h),0>e&&(e=0),0<e&&(document.body.style.transform=
`translateY(${-e}px)`))}}$a(e,h){v(this,e,h||null,n)}pa(){return this.u.pa()}fa(){return this.u.fa()}pg(){const e=this.pa(),h=this.fa();if(this.u.zd()){if(this.ke===e&&h<this.Xb){this.ub=this.Xb-h;this.Lc(this.Xb,this.ub);return}0<this.ub&&(this.ub=0,this.Lc(h,this.ub));this.ke=e;this.Xb=h}this.$a("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Wa()});this.u.uc()&&(-1!==this.Pa&&clearTimeout(this.Pa),this.Rd(e,h,0))}zg(e,h,m){-1!==this.Pa&&clearTimeout(this.Pa);
this.Pa=setTimeout(()=>this.Rd(e,h,m),48)}Rd(e,h,m){const c=this.pa(),k=this.fa();this.Pa=-1;c!=e||k!=h?this.$a("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Wa()}):10>m&&this.zg(c,k,m+1)}mg(e){this.md=e.targetOrientation}Tg(){const e=this.md;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):
screen.webkitLockOrientation?h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Ya(){const e=f.Wa();e&&"any"!==this.md&&this.Tg();v(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.pa(),innerHeight:this.fa()})}Nc(e){console.warn("[Construct 3] Fullscreen request failed: ",
e);v(this,"fullscreenerror",{isFullscreen:f.Wa(),innerWidth:this.pa(),innerHeight:this.fa()})}Rc(e){e?this.u.Cc():this.u.Tc();v(this,"visibilitychange",{hidden:e})}Pd(e,h){"Backspace"===h.key&&A(h);const m=b.get(h.code)||h.code;E(this,e,{code:m,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},d)}eg(e){v(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,
deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},d)}Oc(e,h,m){a(h)||E(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,timeStamp:h.timeStamp},m)}Pc(e,h){if(!a(h)){var m=this.pb;"pointerdown"===e&&0!==m?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");E(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,
pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.pb=h.buttons;this.Oc(h.type,h,g)}}Za(e,h){if(this.sb&&"pointermove"!==e){var m=this.sb;m.hb||(N(m),m.Wb=Date.now())}m=0;"mouse"===h.pointerType&&(m=this.pb);E(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,
movementX:(h.movementX||0)+this.dc,movementY:(h.movementY||0)+this.ec,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);this.ec=this.dc=0;"mouse"===h.pointerType&&(m="mousemove","pointerdown"===e?m="mousedown":"pointerup"===e&&(m="mouseup"),this.Oc(m,h,g),this.pb=h.buttons)}fg(e){this.Ia&&(this.dc+=this.Ia.movementX||0,this.ec+=this.Ia.movementY||0);this.Ia=e;e=this.sb;
if(-1===e.Qa){var h=Date.now(),m=h-e.Wb,c=e.Zg;m>=c&&e.Zd?(e.Wb=h,e.hb=!0,e.Wc(),e.hb=!1):e.Qa=self.setTimeout(e.ue,Math.max(c-m,4))}}yf(){this.Za("pointermove",this.Ia);this.Ia=null}Jb(e,h){for(let m=0,c=h.changedTouches.length;m<c;++m){const k=h.changedTouches[m];E(this,e,{pointerId:k.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:2*(k.radiusX||k.webkitRadiusX||
0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},d)}}Hc(e){window!==window.top&&window.focus();this.Nd(e.target)&&document.activeElement&&!this.Nd(document.activeElement)&&document.activeElement.blur()}Nd(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}pf(){this.Wd||(this.Wd=!0,window.addEventListener("deviceorientation",e=>this.Pf(e)),window.addEventListener("deviceorientationabsolute",
e=>this.Qf(e)))}nf(){this.Vd||(this.Vd=!0,window.addEventListener("devicemotion",e=>this.Of(e)))}Pf(e){v(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}Qf(e){v(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}Of(e){let h=null;var m=e.acceleration;m&&(h=
{x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=e.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;const k=e.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});v(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:m,rotationRate:c,interval:e.interval,timeStamp:e.timeStamp},d)}og(e){var h=this.u;h.ee||(h=h.G,h.style.width=e.styleWidth+"px",h.style.height=e.styleHeight+"px",h.style.marginLeft=e.marginLeft+"px",h.style.marginTop=e.marginTop+"px",this.fe&&
(h.style.display="",this.fe=!1))}ag(e){const h=e.url;e=e.filename;const m=document.createElement("a"),c=document.body;m.textContent=e;m.href=h;m.download=e;c.appendChild(m);m.click();c.removeChild(m)}async hg(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async Zf(e){return await self.C3_GetSvgImageSize(e.blob)}async Jf(e){await q(e.url)}Sc(){var e=
[...this.Ka];this.Ka.clear();if(!this.qa)for(const h of e)(e=h.play())&&e.catch(()=>{this.$b.has(h)||this.Ka.add(h)})}xa(e){if("function"!==typeof e.play)throw Error("missing play function");this.$b.delete(e);let h;try{h=e.play()}catch(m){this.Ka.add(e);return}h&&h.catch(()=>{this.$b.has(e)||this.Ka.add(e)})}Da(e){this.Ka.delete(e);this.$b.add(e)}Eb(e){this.qa=!!e}$f(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Nf(e){if(e.show){this.za||(this.za=document.createElement("div"),
this.za.id="inspectOutline",document.body.appendChild(this.za));var h=this.za;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.za&&(this.za.style.display="none")}jg(){window.C3_RegisterSW&&window.C3_RegisterSW()}Qd(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}Hf(e,h){return this.u.Bd(this.bb,"js-invoke-function",{name:e,params:h},void 0,void 0)}Kc(e){alert(e.message)}rg(e){"entered-fullscreen"===
e?(f.Mb(!0),this.Ya()):"exited-fullscreen"===e?(f.Mb(!1),this.Ya()):console.warn("Unknown wrapper message: ",e)}Eg(e){const h=document.createElement("h1");h.id="exportToVideoMessage";h.textContent=e.message;document.body.prepend(h);document.body.classList.add("exportingToVideo");this.u.G.style.display="";this.u.ef()}Sf(e){this.ae=e.message;-1===this.Zc&&(this.Zc=setTimeout(()=>this.zf(),250))}zf(){this.Zc=-1;const e=document.getElementById("exportToVideoMessage");e&&(e.textContent=this.ae)}Tf(e){window.wh({type:"exported-video",
blob:e.blob,time:e.time})}})}"use strict";async function R(f){if(f.Yg)throw Error("already initialised");f.Yg=!0;var a=f.ic.Gc("dispatchworker.js");f.Yc=await f.ic.oc(a,f.F,{name:"DispatchWorker"});a=new MessageChannel;f.cd=a.port1;f.Yc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.kd=await T(f)}function S(f){return[f.cd,f.kd]}
async function T(f){const a=f.he.length;var b=f.ic.Gc("jobworker.js");b=await f.ic.oc(b,f.F,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;f.Yc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);f.he.push(b);return g.port1}
self.Ye=class{constructor(f){this.ic=f;this.F=f.F;this.F="preview"===f.s?this.F+"workers/":this.F+f.jc;this.ah=Math.min(navigator.hardwareConcurrency||2,16);this.Yc=null;this.he=[];this.kd=this.cd=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.na({qh:!1,rh:"workermain.js",Ra:["scripts/c3runtime.js"],mc:[],od:"",nh:"scripts/",qd:[],ve:"html5"}));"use strict";
{function f(a){a.stopPropagation()}self.na.Sa(class extends self.Ne{constructor(a){super(a,"button")}vd(a,b){const d=document.createElement("input");var g=d;b.isCheckbox?(d.type="checkbox",g=document.createElement("label"),g.appendChild(d),g.appendChild(document.createTextNode("")),g.style.fontFamily="sans-serif",g.style.userSelect="none",g.style.webkitUserSelect="none",g.style.display="inline-block",g.style.color="black"):d.type="button";g.style.position="absolute";g.addEventListener("touchstart",
f);g.addEventListener("touchmove",f);g.addEventListener("touchend",f);g.addEventListener("mousedown",f);g.addEventListener("mouseup",f);g.addEventListener("keydown",f);g.addEventListener("keyup",f);d.addEventListener("click",()=>{var n={isChecked:d.checked};n.elementId=a;E(this,"click",n)});b.id&&(d.id=b.id);this.Bc(g,b);return g}Ld(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}Fc(a){return this.Ld(a)}Bc(a,b){const d=this.Ld(a);d.checked=b.isChecked;d.disabled=!b.isEnabled;a.title=b.title;
a===d?d.value=b.text:a.lastChild.textContent=b.text}})}"use strict";
{let f=!1;self.na.Sa(class extends self.Ta{constructor(a){super(a,"gamepad");this.ge=!!navigator.getGamepads;this.ed=!1;F(this,"is-supported",()=>this.ge);F(this,"ready",()=>this.ig());F(this,"vibrate",b=>this.Xf(b));F(this,"reset-vibrate",b=>this.Wf(b));window.addEventListener("gamepadconnected",b=>this.Uf(b));window.addEventListener("gamepaddisconnected",b=>this.Vf(b));window.addEventListener("unload",()=>this.qg())}Gb(){try{return Array.from(navigator.getGamepads()).filter(a=>a&&a.connected)}catch(a){return f||
(console.warn("[Construct 3] Failed to access gamepads: ",a),f=!0),[]}}ig(){this.ed=!0;for(const a of this.Gb())v(this,"gamepad-connected",{index:a.index,id:a.id});this.ge&&L(this)}Uf(a){this.ed&&(a=a.gamepad,v(this,"gamepad-connected",{index:a.index,id:a.id}))}Vf(a){this.ed&&v(this,"gamepad-disconnected",{index:a.gamepad.index})}wa(){var a=this.Gb();a.length&&(a=a.map(b=>({index:b.index,id:b.id,buttons:b.buttons.map(d=>({pressed:d.pressed,value:d.value})),axes:b.axes})),v(this,"input-update",a))}Kd(a){for(const b of this.Gb())if(b.index===
a)return b;return null}async Xf(a){var b=this.Kd(a.index);if(b&&(b=b.vibrationActuator)&&b.playEffect)try{await b.playEffect("dual-rumble",{duration:a.duration,startDelay:0,weakMagnitude:a.weakMag,strongMagnitude:a.strongMag})}catch(d){console.warn("[Gamepad] Failed to vibrate gamepad: ",d)}}Wf(a){(a=this.Kd(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()}qg(){for(const a of this.Gb()){const b=a.vibrationActuator;b&&b.reset&&b.reset()}}})}"use strict";
{const f=180/Math.PI;self.da=class extends self.Ta{constructor(a){super(a,"audio");this.Sb=this.c=null;this.Ub=this.bd=!1;this.ta=()=>this.Ug();this.aa=[];this.D=[];this.ha=null;this.ie="";this.je=-1;this.rb=new Map;this.gd=1;this.qa=!1;this.nd=0;this.kc=1;this.$c=0;this.me="HRTF";this.$d="inverse";this.ne=600;this.le=1E4;this.pe=1;this.ce=this.ld=!1;this.se=this.u.We();this.ba=new Map;this.Ga=new Set;this.dd=!1;this.hd="";this.Aa=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.dg(b,d);this.Rb=null;
self.C3Audio_GetOutputStream=()=>this.Yf();self.C3Audio_DOMInterface=this;K(this,[["create-audio-context",b=>this.uf(b)],["play",b=>this.tg(b)],["stop",b=>this.Rg(b)],["stop-all",()=>this.Sg()],["set-paused",b=>this.Kg(b)],["set-volume",b=>this.Pg(b)],["fade-volume",b=>this.Af(b)],["set-master-volume",b=>this.Ig(b)],["set-muted",b=>this.Jg(b)],["set-silent",b=>this.Mg(b)],["set-looping",b=>this.Hg(b)],["set-playback-rate",b=>this.Lg(b)],["seek",b=>this.Ag(b)],["preload",b=>this.ug(b)],["unload",b=>
this.Vg(b)],["unload-all",()=>this.Wg()],["set-suspended",b=>this.Ng(b)],["get-suspended",()=>this.Ef()],["add-effect",b=>this.Gd(b)],["set-effect-param",b=>this.Dg(b)],["remove-effects",b=>this.wg(b)],["tick",b=>this.ng(b)],["load-state",b=>this.bg(b)]])}async uf(a){a.isiOSCordova&&(this.ld=!0);this.nd=a.timeScaleMode;this.me=["equalpower","HRTF","soundfield"][a.panningModel];this.$d=["linear","inverse","exponential"][a.distanceModel];this.ne=a.refDistance;this.le=a.maxDistance;this.pe=a.rolloffFactor;
var b={latencyHint:a.latencyHint};this.se||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.c=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.c=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.Hd();this.c.onstatechange=()=>{"running"!==this.c.state&&this.Hd()};this.Sb=this.c.createGain();this.Sb.connect(this.c.destination);b=a.listenerPos;this.c.listener.setPosition(b[0],b[1],b[2]);this.c.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=
()=>this.pc();try{await Promise.all(a.preloadList.map(d=>this.Hb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.c.sampleRate}}Hd(){this.Ub||(this.bd=!1,window.addEventListener("pointerup",this.ta,!0),window.addEventListener("touchend",this.ta,!0),window.addEventListener("click",this.ta,!0),window.addEventListener("keydown",this.ta,!0),this.Ub=!0)}wf(){this.Ub&&(this.bd=!0,window.removeEventListener("pointerup",this.ta,!0),
window.removeEventListener("touchend",this.ta,!0),window.removeEventListener("click",this.ta,!0),window.removeEventListener("keydown",this.ta,!0),this.Ub=!1)}Ug(){if(!this.bd){var a=this.c;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.wf()}}W(){return this.c}pc(){return this.c.currentTime}ua(){return this.Sb}xd(a){return(a=this.ba.get(a.toLowerCase()))?a[0].P():this.ua()}we(a,
b){a=a.toLowerCase();let d=this.ba.get(a);d||(d=[],this.ba.set(a,d));b.Gg(d.length);b.Og(a);d.push(b);this.Td(a)}Td(a){let b=this.ua();const d=this.ba.get(a);if(d&&d.length){b=d[0].P();for(let g=0,n=d.length;g<n;++g){const q=d[g];g+1===n?q.S(this.ua()):q.S(d[g+1].P())}}for(const g of this.ma(a))g.cf(b);this.Aa&&this.hd===a&&(this.Aa.disconnect(),this.Aa.connect(b))}Ab(){return this.gd}Bb(){return this.qa}Fg(){this.ce=!0}Pe(a,b){return b?this.u.Xg(a).then(d=>{const g=this.c.createBuffer(1,d.length,
48E3);g.getChannelData(0).set(d);return g}):new Promise((d,g)=>{this.c.decodeAudioData(a,d,g)})}xa(a){this.u.xa(a)}Da(a){this.u.Da(a)}Cd(a){let b=0;for(let d=0,g=this.D.length;d<g;++d){const n=this.D[d];this.D[b]=n;n.L===a?n.f():++b}this.D.length=b}df(){let a=0;for(let b=0,d=this.aa.length;b<d;++b){const g=this.aa[b];this.aa[a]=g;g.va()?g.f():++a}this.aa.length=a}*ma(a){if(a)for(const b of this.D)self.da.Qe(b.Z,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Hb(a,b,d,g,n){for(const q of this.aa)if(q.Va()===
b)return await U(q),q;if(n)return null;g&&(this.ld||this.ce)&&this.df();n="audio/webm; codecs=opus"===d&&!this.se;g&&n&&this.Fg();a=!g||this.ld||n?new self.Ke(this,a,b,d,g,n):new self.Ie(this,a,b,d,g);this.aa.push(a);await U(a);return a}async Ec(a,b,d,g,n){for(const q of this.D)if(q.Va()===b&&(q.nc()||n))return q.gf(g),q;a=await this.Hb(a,b,d,n);g="html5"===a.Vc?new self.Je(a.i,a,g):new self.Le(a.i,a,g);this.D.push(g);return g}lf(a){let b=this.rb.get(a);if(!b){let d=null;b={pd:0,mh:new Promise(g=>
d=g),resolve:d};this.rb.set(a,b)}b.pd++}xg(a){const b=this.rb.get(a);if(!b)throw Error("expected pending tag");b.pd--;0===b.pd&&(b.resolve(),this.rb.delete(a))}Ac(a){a||(a=this.ie);return(a=this.rb.get(a))?a.mh:Promise.resolve()}Ib(){if(0<this.Ga.size)L(this);else for(const a of this.D)if(a.yd()){L(this);break}}wa(){for(var a of this.Ga)a.wa();a=this.pc();for(var b of this.D)b.wa(a);b=this.D.filter(d=>d.yd()).map(d=>d.Ua());v(this,"state",{tickCount:this.je,audioInstances:b,analysers:[...this.Ga].map(d=>
d.Se())});0===b.length&&0===this.Ga.size&&this.Vb&&(this.u.yg(this.te),this.Vb=!1)}wc(a,b,d){v(this,"trigger",{type:a,tag:b,aiid:d})}async tg(a){const b=a.originalUrl,d=a.url,g=a.type,n=a.isMusic,q=a.tag,w=a.isLooping,B=a.vol,D=a.pos,x=a.panning;let y=a.off;0<y&&!a.trueClock&&(this.c.getOutputTimestamp?(a=this.c.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+this.c.currentTime);this.ie=q;this.lf(q);try{this.ha=await this.Ec(b,d,g,q,n),x?(this.ha.Db(!0),this.ha.ff(x.x,
x.y,x.angle,x.innerAngle,x.outerAngle,x.outerGain),x.hasOwnProperty("uid")&&this.ha.hf(x.uid)):this.ha.Db(!1),this.ha.Play(w,B,D,y)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.xg(q)}L(this)}Rg(a){a=a.tag;for(const b of this.ma(a))b.oa()}Sg(){for(const a of this.D)a.oa()}Kg(a){const b=a.tag;a=a.paused;for(const d of this.ma(b))a?d.Xa():d.Cb();this.Ib()}Pg(a){const b=a.tag;a=a.vol;for(const d of this.ma(b))d.Fb(a)}async Af(a){const b=a.tag,d=a.vol,
g=a.duration;a=a.stopOnEnd;await this.Ac(b);for(const n of this.ma(b))n.Re(d,g,a);this.Ib()}Ig(a){this.gd=a.vol;for(const b of this.D)b.Ob()}Jg(a){const b=a.tag;a=a.isMuted;for(const d of this.ma(b))d.Dd(a)}Mg(a){this.qa=a.isSilent;this.u.Eb(this.qa);for(const b of this.D)b.Nb()}Hg(a){const b=a.tag;a=a.isLooping;for(const d of this.ma(b))d.yc(a)}async Lg(a){const b=a.tag;a=a.rate;await this.Ac(b);for(const d of this.ma(b))d.Fd(a)}async Ag(a){const b=a.tag;a=a.pos;await this.Ac(b);for(const d of this.ma(b))d.xc(a)}async ug(a){const b=
a.originalUrl,d=a.url,g=a.type;a=a.isMusic;try{await this.Ec(b,d,g,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async Vg(a){if(a=await this.Hb("",a.url,a.type,a.isMusic,!0))a.f(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}Wg(){for(const a of this.aa)a.f();this.aa.length=0}Ng(a){a=a.isSuspended;!a&&this.c.resume&&this.c.resume();for(const b of this.D)b.zc(a);a&&this.c.suspend&&this.c.suspend()}Ef(){return this.c?this.c.state:"suspended"}ng(a){this.kc=a.timeScale;
this.$c=a.gameTime;this.je=a.tickCount;if(0!==this.nd)for(var b of this.D)b.Fa();(b=a.listenerPos)&&this.c.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.D)g.ga===a&&g.Ed(d.x,d.y,d.angle)}}async Gd(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.Ce(this,...g);else if("delay"===b)g=new self.Ae(this,...g);else if("convolution"===b){b=null;try{b=await this.Hb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",
n);return}g=new self.ze(this,b.$,...g);g.Bg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.De(this,...g);else if("phaser"===b)g=new self.Fe(this,...g);else if("gain"===b)g=new self.Ee(this,...g);else if("tremolo"===b)g=new self.He(this,...g);else if("ringmod"===b)g=new self.Ge(this,...g);else if("distortion"===b)g=new self.Be(this,...g);else if("compressor"===b)g=new self.ye(this,...g);else if("analyser"===b)g=new self.xe(this,...g);else throw Error("invalid effect type");this.we(d,
g);this.Sd()}Dg(a){const b=a.index,d=a.param,g=a.value,n=a.ramp,q=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,g,n,q),this.Sd())}wg(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const d of b)d.f();this.ba.delete(a);this.Td(a)}}kf(a){this.Ga.add(a);this.Ib()}vg(a){this.Ga.delete(a)}Sd(){this.dd||(this.dd=!0,Promise.resolve().then(()=>this.xf()))}xf(){const a={};for(const [b,d]of this.ba)a[b]=d.map(g=>g.Ua());v(this,"fxstate",{fxstate:a});this.dd=!1}async bg(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.D)d.va()&&1===b||(d.va()||2!==b)&&d.oa();for(const g of this.ba.values())for(const n of g)n.f();this.ba.clear();this.kc=a.timeScale;this.$c=a.gameTime;d=a.listenerPos;this.c.listener.setPosition(d[0],d[1],d[2]);this.qa=a.isSilent;this.u.Eb(this.qa);this.gd=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(n=>this.Gd(n))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.If(g,b)));this.Ib()}async If(a,b){if(3!==
b){var d=a.bufferOriginalUrl,g=a.bufferUrl,n=a.bufferType,q=a.isMusic,w=a.tag,B=a.isLooping,D=a.volume,x=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.Ec(d,g,n,w,q)}catch(y){console.error("[Construct 3] Audio: error loading audio state: ",y);return}b.af(a.pan);b.Play(B,D,x,0);a.isPlaying||b.Xa();b.Jc(a)}}}dg(a,b){this.Aa&&this.Aa.disconnect();this.hd=b.toLowerCase();this.Aa=this.c.createMediaStreamSource(a);this.Aa.connect(this.xd(this.hd))}Yf(){this.Rb||(this.Rb=this.c.createMediaStreamDestination(),
this.Sb.connect(this.Rb));return this.Rb.stream}static Qe(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static jf(a){return a*f}static Oe(a){return Math.pow(10,a/20)}static wd(a){return Math.max(Math.min(self.da.Oe(a),1),0)}static $e(a){return Math.log(a)/Math.log(10)*20}static Ze(a){return self.da.$e(Math.max(Math.min(a,1),0))}static hh(a,b){return 1-Math.exp(-b*a)}};self.na.Sa(self.da)}"use strict";function U(f){f.Yb||(f.Yb=f.Ic());return f.Yb}
self.sd=class{constructor(f,a,b,d,g){this.i=f;this.dh=a;this.Ba=b;this.R=d;this.$g=g;this.Vc="";this.Yb=null}f(){this.Yb=this.i=null}Ic(){}W(){return this.i.W()}rc(){return this.dh}Va(){return this.Ba}qc(){return this.R}va(){return this.$g}ea(){}};"use strict";
self.Ie=class extends self.sd{constructor(f,a,b,d,g){super(f,a,b,d,g);this.Vc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.lb=this.mb=null;this.K.addEventListener("canplaythrough",()=>!0);this.qb=this.W().createGain();this.ob=null;this.K.addEventListener("canplay",()=>{this.mb&&(this.mb(),this.lb=this.mb=null);!this.ob&&this.K&&(this.ob=this.W().createMediaElementSource(this.K),this.ob.connect(this.qb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.Ba}' error: `,n);this.lb&&(this.lb(n),this.lb=this.mb=null)})}f(){this.i.Cd(this);this.qb.disconnect();this.qb=null;this.ob.disconnect();this.ob=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.f()}Ic(){return new Promise((f,a)=>{this.mb=f;this.lb=a;this.K.src=this.Ba})}O(){return this.K}ea(){return this.K.duration}};"use strict";
async function V(f){if(f.ya)return f.ya;var a=f.i.u;if("cordova"===a.s&&a.Ad(f.Ba)&&a.ib)f.ya=await a.yb(f.Ba);else{a=await fetch(f.Ba);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.ya=await a.arrayBuffer()}}async function W(f){if(f.$)return f.$;f.$=await f.i.Pe(f.ya,f.bh);f.ya=null}
self.Ke=class extends self.sd{constructor(f,a,b,d,g,n){super(f,a,b,d,g);this.Vc="webaudio";this.$=this.ya=null;this.bh=!!n}f(){this.i.Cd(this);this.$=this.ya=null;super.f()}async Ic(){try{await V(this),await W(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.Ba}': `,f)}}ea(){return this.$?this.$.duration:0}};"use strict";
{let f=0;self.td=class{constructor(a,b,d){this.i=a;this.L=b;this.Z=d;this.Pb=f++;this.M=this.W().createGain();this.M.connect(this.ua());this.B=null;this.jb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.I=!0;this.V=this.la=this.H=!1;this.vb=1;this.Ha=!1;this.sa=1;a=this.i.nd;this.fd=1===a&&!this.va()||2===a;this.fb=this.ga=-1;this.re=!1}f(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ua(){return this.i.xd(this.Z)}Ab(){return this.i.Ab()}zb(){return this.fd?
this.i.$c:performance.now()/1E3}rc(){return this.L.rc()}Va(){return this.L.Va()}qc(){return this.L.qc()}va(){return this.L.va()}gf(a){this.Z=a}T(){}nc(){}IsPlaying(){return!this.I&&!this.H&&!this.T()}yd(){return!this.I&&!this.T()}Ca(){}ea(){return this.L.ea()}Play(){}oa(){}Xa(){}Cb(){}Fb(a){this.vb=a;this.M.gain.cancelScheduledValues(0);this.fb=-1;this.M.gain.value=this.sc()}Re(a,b,d){if(!this.Ha){a*=this.Ab();var g=this.M.gain;g.cancelScheduledValues(0);var n=this.i.pc();b=n+b;g.setValueAtTime(g.value,
n);g.linearRampToValueAtTime(a,b);this.vb=a;this.fb=b;this.re=d}}Ob(){this.Fb(this.vb)}wa(a){-1!==this.fb&&a>=this.fb&&(this.fb=-1,this.re&&this.oa(),this.i.wc("fade-ended",this.Z,this.Pb))}sc(){const a=this.vb*this.Ab();return isFinite(a)?a:0}Dd(a){a=!!a;this.Ha!==a&&(this.Ha=a,this.Nb())}Bb(){return this.i.Bb()}Nb(){}yc(){}Fd(a){this.sa!==a&&(this.sa=a,this.Fa())}Fa(){}xc(){}zc(){}Db(a){a=!!a;this.jb!==a&&((this.jb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.me,this.B.distanceModel=
this.i.$d,this.B.refDistance=this.i.ne,this.B.maxDistance=this.i.le,this.B.rolloffFactor=this.i.pe),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ua())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ua())))}ff(a,b,d,g,n,q){this.jb&&(this.Ed(a,b,d),a=self.da.jf,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=q)}Ed(a,b,d){this.jb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(d),this.ja[1]=Math.sin(d),this.ja[2]=0,this.B.setPosition(...this.ka),
this.B.setOrientation(...this.ja))}hf(a){this.ga=a}tc(){}cf(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ua(){return{aiid:this.Pb,tag:this.Z,duration:this.ea(),volume:this.vb,isPlaying:this.IsPlaying(),playbackTime:this.Ca(),playbackRate:this.sa,uid:this.ga,bufferOriginalUrl:this.rc(),bufferUrl:"",bufferType:this.qc(),isMusic:this.va(),isLooping:this.V,isMuted:this.Ha,resumePosition:this.tc(),pan:this.Te()}}Jc(a){this.Fd(a.playbackRate);this.Dd(a.isMuted)}Te(){if(!this.B)return null;const a=
this.B;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}af(a){if(a){this.Db(!0);a=this.B;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.Db(!1)}}}"use strict";
self.Je=class extends self.td{constructor(f,a,b){super(f,a,b);this.L.qb.connect(this.M);this.L.onended=()=>this.Mc()}f(){this.oa();this.L.qb.disconnect();super.f()}O(){return this.L.O()}Mc(){this.I=!0;this.ga=-1;this.i.wc("ended",this.Z,this.Pb)}T(){return this.O().ended}nc(){return this.I?!0:this.T()}Ca(){let f=this.O().currentTime;this.V||(f=Math.min(f,this.ea()));return f}Play(f,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==f&&(d.loop=f);this.Fb(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Va()}' to position '${b}': `,g)}this.i.xa(d);this.H=this.I=!1;this.V=f;this.sa=1}oa(){const f=this.O();f.paused||f.pause();this.i.Da(f);this.I=!0;this.H=!1;this.ga=-1}Xa(){if(!(this.H||this.I||this.T())){var f=this.O();f.paused||f.pause();this.i.Da(f);this.H=!0}}Cb(){!this.H||this.I||this.T()||(this.i.xa(this.O()),this.H=!1)}Nb(){this.O().muted=this.Ha||this.Bb()}yc(f){f=!!f;this.V!==f&&
(this.V=f,this.O().loop=f)}Fa(){let f=this.sa;this.fd&&(f*=this.i.kc);try{this.O().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}xc(f){if(!this.I&&!this.T())try{this.O().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}tc(){return this.Ca()}zc(f){f?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.xa(this.O()),this.la=!1)}};"use strict";
function X(f){f.j&&f.j.disconnect();f.j=null;f.ab=null}
self.Le=class extends self.td{constructor(f,a,b){super(f,a,b);this.j=null;this.ac=d=>this.Mc(d);this.ad=!0;this.ab=null;this.N=this.bc=this.cc=0;this.jd=1}f(){this.oa();X(this);this.ac=null;super.f()}Mc(f){this.H||this.la||f.target!==this.ab||(this.I=this.ad=!0,this.ga=-1,X(this),this.i.wc("ended",this.Z,this.Pb))}T(){return!this.I&&this.j&&this.j.loop||this.H?!1:this.ad}nc(){return!this.j||this.I?!0:this.T()}Ca(){let f;f=this.H?this.N:this.bc+(this.zb()-this.cc)*this.sa;this.V||(f=Math.min(f,this.ea()));
return f}Play(f,a,b,d){this.jd=1;this.Fb(a);X(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.$;this.j.connect(this.M);this.ab=this.j;this.j.onended=this.ac;this.j.loop=f;this.j.start(d,b);this.H=this.I=this.ad=!1;this.V=f;this.sa=1;this.cc=this.zb();this.bc=b}oa(){if(this.j)try{this.j.stop(0)}catch(f){}this.I=!0;this.H=!1;this.ga=-1}Xa(){this.H||this.I||this.T()||(this.N=this.Ca(),this.V&&(this.N%=this.ea()),this.H=!0,this.j.stop(0))}Cb(){!this.H||this.I||this.T()||(X(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.ac,this.j.loop=this.V,this.Ob(),this.Fa(),this.j.start(0,this.N),this.cc=this.zb(),this.bc=this.N,this.H=!1)}sc(){return super.sc()*this.jd}Nb(){this.jd=this.Ha||this.Bb()?0:1;this.Ob()}yc(f){f=!!f;this.V!==f&&(this.V=f,this.j&&(this.j.loop=f))}Fa(){let f=this.sa;this.fd&&(f*=this.i.kc);this.j&&(this.j.playbackRate.value=f)}xc(f){this.I||this.T()||(this.H?this.N=f:(this.Xa(),this.N=f,this.Cb()))}tc(){return this.N}zc(f){f?
this.IsPlaying()?(this.la=!0,this.N=this.Ca(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.la=!1:this.la&&(X(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.ac,this.j.loop=this.V,this.Ob(),this.Fa(),this.j.start(0,this.N),this.cc=this.zb(),this.bc=this.N,this.la=!1)}Jc(f){super.Jc(f);this.N=f.resumePosition}};"use strict";
{class f{constructor(a){this.i=a;this.c=a.W();this.de=-1;this.R=this.Z="";this.g=null}f(){this.c=null}Gg(a){this.de=a}Og(a){this.Z=a}o(){return this.c.createGain()}P(){}S(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var n=this.c.currentTime;g+=n;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,g)}}}Ua(){return{type:this.R,tag:this.Z,params:this.g}}}
self.Ce=class extends f{constructor(a,b,d,g,n,q,w){super(a);this.R="filter";this.g=[b,d,g,n,q,w];this.l=this.o();this.b=this.o();this.b.gain.value=w;this.a=this.o();this.a.gain.value=1-w;this.A=this.c.createBiquadFilter();this.A.type=b;this.A.frequency.value=d;this.A.detune.value=g;this.A.Q.value=n;this.A.gain.vlaue=q;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b)}f(){this.l.disconnect();this.A.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.A.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.A.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.A.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.A.gain,b,d,g)}}};self.Ae=class extends f{constructor(a,b,d,g){super(a);this.R="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.nb=this.o();this.U=this.c.createDelay(b);this.U.delayTime.value=b;this.eb=this.o();this.eb.gain.value=d;this.l.connect(this.nb);this.l.connect(this.a);this.nb.connect(this.b);this.nb.connect(this.U);this.U.connect(this.eb);this.eb.connect(this.nb)}f(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.nb.disconnect();this.U.disconnect();this.eb.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){const n=self.da.wd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=n(b);this.m(this.eb.gain,n(b),d,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,g)}}};self.ze=class extends f{constructor(a,b,d,g){super(a);this.R="convolution";this.g=[d,g];this.Yd=this.Xd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.cb=this.c.createConvolver();this.cb.normalize=d;this.cb.buffer=b;this.l.connect(this.cb);this.l.connect(this.a);this.cb.connect(this.b)}f(){this.l.disconnect();this.cb.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}Bg(a,b){this.Xd=a;this.Yd=b}Ua(){const a=
super.Ua();a.bufferOriginalUrl=this.Xd;a.bufferUrl="";a.bufferType=this.Yd;return a}};self.De=class extends f{constructor(a,b,d,g,n,q){super(a);this.R="flanger";this.g=[b,d,g,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.gb=this.o();this.gb.gain.value=n;this.U=this.c.createDelay(b+d);this.U.delayTime.value=b;this.v=this.c.createOscillator();this.v.frequency.value=g;this.J=this.o();this.J.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.gb);this.gb.connect(this.U);this.v.connect(this.J);this.J.connect(this.U.delayTime);this.v.start(0)}f(){this.v.stop(0);this.l.disconnect();this.U.disconnect();this.v.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();this.gb.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.J.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.v.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.gb.gain,b/100,d,g)}}};self.Fe=class extends f{constructor(a,b,d,g,n,q,w){super(a);this.R="phaser";this.g=[b,d,g,n,q,w];this.l=this.o();this.a=this.o();this.a.gain.value=1-w/2;this.b=this.o();this.b.gain.value=w/2;this.A=this.c.createBiquadFilter();this.A.type="allpass";this.A.frequency.value=b;this.A.detune.value=
d;this.A.Q.value=g;this.v=this.c.createOscillator();this.v.frequency.value=q;this.J=this.o();this.J.gain.value=n;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b);this.v.connect(this.J);this.J.connect(this.A.frequency);this.v.start(0)}f(){this.v.stop(0);this.l.disconnect();this.A.disconnect();this.v.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.A.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.A.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.A.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.J.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.v.frequency,b,d,g)}}};self.Ee=class extends f{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){const n=self.da.wd;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,g)}}};self.He=class extends f{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.v=this.c.createOscillator();this.v.frequency.value=b;this.J=this.o();this.J.gain.value=d/2;this.v.connect(this.J);this.J.connect(this.h.gain);this.v.start(0)}f(){this.v.stop(0);this.v.disconnect();
this.J.disconnect();this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,g);this.m(this.J.gain,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.v.frequency,b,d,g)}}};self.Ge=class extends f{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.tb=this.o();this.tb.gain.value=
0;this.v=this.c.createOscillator();this.v.frequency.value=b;this.v.connect(this.tb.gain);this.v.start(0);this.l.connect(this.tb);this.l.connect(this.a);this.tb.connect(this.b)}f(){this.v.stop(0);this.v.disconnect();this.tb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,g);
this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.v.frequency,b,d,g)}}};self.Be=class extends f{constructor(a,b,d,g,n,q){super(a);this.R="distortion";this.g=[b,d,g,n,q];this.l=this.o();this.hc=this.o();this.fc=this.o();this.Cg(g,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.lc=this.c.createWaveShaper();this.Xc=new Float32Array(65536);this.Cf(b,d);this.lc.curve=this.Xc;this.l.connect(this.hc);this.l.connect(this.a);this.hc.connect(this.lc);this.lc.connect(this.fc);
this.fc.connect(this.b)}f(){this.l.disconnect();this.hc.disconnect();this.lc.disconnect();this.fc.disconnect();this.b.disconnect();this.a.disconnect();super.f()}Cg(a,b){.01>a&&(a=.01);this.hc.gain.value=a;this.fc.gain.value=Math.pow(1/a,.6)*b}Cf(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.Qg(g,a,b);this.Xc[32768+d]=g;this.Xc[32768-d-1]=-g}}Qg(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.da.hh(g-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.ye=class extends f{constructor(a,b,d,g,n,q){super(a);this.R="compressor";this.g=[b,d,g,n,q];this.h=this.c.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=n;this.h.release.value=q}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.xe=class extends f{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.c.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.be=new Float32Array(this.h.frequencyBinCount);this.qe=new Uint8Array(b);this.oe=this.La=0;this.i.kf(this)}f(){this.i.vg(this);this.h.disconnect();super.f()}wa(){this.h.getFloatFrequencyData(this.be);this.h.getByteTimeDomainData(this.qe);const a=this.h.fftSize;let b=this.La=0;for(var d=0;d<a;++d){let g=(this.qe[d]-128)/128;0>g&&(g=-g);
this.La<g&&(this.La=g);b+=g*g}d=self.da.Ze;this.La=d(this.La);this.oe=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Se(){return{tag:this.Z,index:this.de,peak:this.La,rms:this.oe,binCount:this.h.frequencyBinCount,freqBins:this.be}}}}"use strict";function Y(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>v(f,"sw-message",a.data))}
function Z(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(f):screen.webkitLockOrientation?a=screen.webkitLockOrientation(f):screen.mozLockOrientation?a=screen.mozLockOrientation(f):screen.msLockOrientation&&(a=screen.msLockOrientation(f));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.na.Sa(class extends self.Ta{constructor(f){super(f,"browser");this.s="";K(this,[["get-initial-state",a=>{this.s=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Y(this)],["alert",a=>this.Kc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Qc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Z(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,
"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.vh||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.s||"macos-wkwebview"===this.s)self.na.Mb(!0),this.u.Uc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===
a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.s||"macos-wkwebview"===this.s?(self.na.Mb(!1),this.u.Uc({type:"set-fullscreen",
fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{v(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{v(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{v(this,"hashchange",
{location:location.toString()})});document.addEventListener("backbutton",()=>{v(this,"backbutton")})}Kc(f){alert(f.message)}Qc(f){f=f.isFocus;if("nwjs"===this.s){const a="nwjs"===this.s?nw.Window.get():null;f?a.focus():a.blur()}else f?window.focus():window.blur()}});
